### ISSUE TITLE
pg-promise hint

### ISSUE THREAD

**Issue by vitaly-t** [medic/couch2pg#1]
for this line:
```js
db = require('pg-promise')({ 'promiseLib': Promise })(PG_URL);
```
passing in `{ 'promiseLib': Promise }` doesn't do anything useful, because this is the default ;) might as well pass in nothing ;)

**Comment by SCdF** [comment]
Good point! Those instructions were copied from the code, which does do this, because Promise === rsvp's implementation, because we support very old versions of node (0.12) which did not have native promise support.

I'll clean up the readme to presume you use a more modern version of node.

**Comment by SCdF** [comment]
Done.

**Comment by vitaly-t** [comment]
@SCdF and why are using such an ancient version of `pg-promise` (3.0.0)? The current one is 5.4.2

Also, you do need to include `pg` when already including `pg-promise` :wink:
