### ISSUE TITLE
Deprecate couch2pg

### ISSUE THREAD

**Issue by garethbowen** [medic/couch2pg#46]
`couch2pg` and `cht-couch2pg` are both being sunsetted in favour of a different approach https://github.com/medic/cht-sync and https://github.com/medic/cht-pipeline. Please update documentation to make this clear.

This includes

- [x] updating the README.md in both repos to state that they are sunsetted and directing people to the new docs
- [x] updating or removing any and all docs on the docs site that reference couch2pg or cht-couch2pg
- [x] updating the tech radar (which already says "stop" using couch2pg) to direct viewers to cht-sync
- [x] announcing the deprecation on slack, tagging app devs specifically
- [x] announcing the deprecation on the forum

**Comment by garethbowen** [comment]
Related: https://github.com/medic/cht-docs/pull/1518

**Comment by andrablaj** [comment]
Related: https://github.com/medic/cht-tech-radar-implementers/pull/14

**Comment by andrablaj** [comment]
Slack messages: [#development channel](https://medic.slack.com/archives/C024KTGRW/p1727869429263839), [#app-services channel](https://medic.slack.com/archives/C0813CQRX/p1727869444508769).

**Comment by andrablaj** [comment]
[Forum post](https://forum.communityhealthtoolkit.org/t/sunsetting-couch2pg-and-cht-couch2pg/4121).
