### ISSUE TITLE
Consider filtering out feedback docs from the medic database

### ISSUE THREAD

**Issue by michaelkohn** [medic/couch2pg#7]
A large number of feedback docs are being created and replicated to PostgreSQL.  While the size of the documents is not necessarily huge from a space perspective, we have only one table in PostgreSQL (couchdb) and we are replicating a lot of unnecessary documents.  In one project, over 20% of total documents (out of 700k+) are feedback docs.  While creative use of indexes can help with the impact on query performance, it might be worth looking into moving feedback docs into a separate database, not replicating these documents and/or having a process of reviewing them and then removing them.

**Comment by garethbowen** [comment]
Filtering is happening as part of moving feedback docs to a separate couchdb.
