### ISSUE TITLE
Postgres needs access to scheduling information

### ISSUE THREAD

**Issue by btbonval** [medic/couch2pg#9]
Schedules could possibly change over time.

Within postgres, if we entirely recreate schedules (duplicating nools logic), then we might miss when parameters change _and_ we're exposing ourselves to loss of sync in logic.

For LG, we (or our partners) might hard code certain schedule parameters directly into analytics views in the short term.

In the long term, it'd be great if we had access to some kind of task trail, or nools debug, or something like this which preserves the logic performed in a way which can be queried and utilized accurately, post hoc. If a task was created using logic and parameters from 3 months ago, we'd like to have some way to know the result of that task as it was calculated 3 months ago.

**Comment by garethbowen** [comment]
This is fixed by storing tasks to disk.
